version: "3.8"
services:
  humble_py3d_2000ada:
    container_name: humble_py3d_2000ada
    image: humble_py3d_2000ada
    privileged: true
    user: ros
    network_mode: host
    stdin_open: true # docker run -i
    tty: true # docker run -t
    runtime: nvidia
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVI=1

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/dot.Xauthority
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - /dev/bus/usb:/dev/bus/usb
      - type: bind
        source: ../../units_ws
        target: /home/code
    build:
      context: .
      dockerfile: ./humble_py3d_2000ada/Dockerfile
      args:
        USERNAME: ros
    command: /bin/sh -c "while sleep 1000; do :; done"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
